### ISSUE TITLE
Need some way to calculate amount for redeem function if i know amount i want to receive.

### ISSUE THREAD

**Issue by pash7ka** [Stakedllc/robo-advisor-yield#15]
## Why 
I'm writing a smart-contract system that may use RAY to hold DAI while they are not needed.
One of the operation i need - redeem some amount of DAI. 
Currently if i provide some amount to `PortfolioManager.redeem()`, i may receive smaller amount, because of fee.
I need some way either to specify actual amount that `redeem()` will send, or to calculate an amount to provide to current implementation of redeem().

## Solution
It would be perfect, if you can add a function to `PortfolioManager` simmilar to `redeemUnderlying` function of cDAI, which accepts "netto" amount of DAI to redeem.

## Considerations
Alternatively, please provide me with some way to calculate `valueToWithdraw` from `valueAfterFee`.

**Comment by dpurhar27** [comment]
Hey @pash7ka !

This is a good question as there isn't any helper function documented for this behaviour. 

The good news is the solution is simple for you because RAY has removed fees for the mid-term. This means the amount you enter for the parameter `valueToWithdraw` in `redeem()` is the amount you will receive, as `valueAfterFee` will always be zero.

Going forward, when RAY re-implements fees we'll be using a new mechanism which incorporates the fee into the token's value. Fees will inherently be incorporated into the token's value - currently they are not (therefore `tokenValue` and `tokenValueAfterFee` aren't the same). This means you won't have this same issue then, and you won't need to change your integration in the future to handle it when we add fees again. 

Please let me know if this makes sense or if you have any questions!

**Comment by pash7ka** [comment]
Thank you @dpurhar27 !
This perfectly solves my issue.

**Comment by dpurhar27** [comment]
My pleasure - happy to hear that!
